name: Set assignees

on:
  pull_request:
    types: opened

jobs:
  assign:
    name: 担当者を自動でセット
    runs-on: ubuntu-18.04
    steps:
      - name: 担当者を自動でセット
        env:
          ASSIGNEES: "${{ github.actor }}"
        run: |
          assignee_count=$(cat ${{ github.event_path }} | jq '.pull_request.assignees | length')
          if [[ 0 == $assignee_count ]]; then
            assignees=$(echo "\"${ASSIGNEES// /}\"" | jq 'split(",")')
            curl -X POST \
                 -H "Content-Type: application/json" \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d "{ \"assignees\": $assignees }" \
                 https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees
          fi
